# Generated by Django 2.2.5 on 2019-12-04 04:14
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='客户号')),
                ('customer_name', models.CharField(max_length=20, verbose_name='客户名称')),
                ('addr', models.CharField(max_length=40, verbose_name='客户住址')),
                ('tel_no', models.CharField(max_length=12, verbose_name='客户电话')),
                ('zip_code', models.CharField(blank=True, max_length=6, null=True, verbose_name='邮政编码')),
            ],
            options={
                'verbose_name': '顾客信息表',
                'verbose_name_plural': '顾客信息表',
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_no', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='员工编号')),
                ('emp_name', models.CharField(max_length=10, verbose_name='员工姓名')),
                ('sex', models.CharField(choices=[('F', 'Female'), ('M', 'Man')], max_length=1, verbose_name='性别')),
                ('dept', models.CharField(max_length=4, verbose_name='所属部门')),
                ('title', models.CharField(max_length=6, verbose_name='职称')),
                ('date_hired', models.DateField(blank=True, null=True, verbose_name='入职时间')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='生日')),
                ('salary', models.IntegerField(verbose_name='工资')),
                ('addr', models.CharField(blank=True, max_length=50, null=True, verbose_name='住址')),
                ('Mod_date', models.DateTimeField(auto_now=True, verbose_name='操作者')),
                ('emp_img', models.ImageField(default="", verbose_name='员工图片', upload_to='emp/')),
            ],
            options={
                'verbose_name': '员工信息表',
                'verbose_name_plural': '员工信息表',
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('prod_id', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='产品编号')),
                ('qty', models.IntegerField(verbose_name='销售数量')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='单价')),
                ('order_date', models.DateField(blank=True, null=True, verbose_name='订单日期')),
            ],
            options={
                'verbose_name': '售货明细表',
                'verbose_name_plural': '售货明细表',
                'db_table': 'sale_item',
                'ordering': ['order_no'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('prod_id', models.OneToOneField(max_length=5, on_delete=True, primary_key=True, serialize=False, to='salesapp.SaleItem', verbose_name='产品编号')),
                ('prod_name', models.CharField(max_length=20, verbose_name='产品名称')),
                ('prod_img', models.ImageField(verbose_name='产品图片', default="", upload_to='./'))
            ],
            options={
                'verbose_name': '产品信息表',
                'verbose_name_plural': '产品信息表',
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('order_no', models.IntegerField(primary_key=True, serialize=False, verbose_name='订单编号')),
                ('tot_amt', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='订单金额')),
                ('order_date', models.DateField(verbose_name='订货日期', null=True, blank=True)),
                ('ship_date', models.DateField(verbose_name='出货日期', null=True, blank=True)),
                ('invoice_no', models.CharField(max_length=10, unique=True, verbose_name='发票号码')),
                ('customer_id', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='salesapp.Customer')),
                ('sale_id', models.ForeignKey(max_length=5, on_delete=django.db.models.deletion.CASCADE, to='salesapp.Employee')),
            ],
            options={
                'verbose_name': '销售信息表',
                'verbose_name_plural': '销售信息表',
                'db_table': 'sales',
            },
        ),
        migrations.AddField(
            model_name='saleitem',
            name='order_no',
            field=models.ForeignKey(on_delete=True, to='salesapp.Sales'),
        ),
    ]
