# Generated by Django 2.2.5 on 2019-12-18 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salesapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saleitem',
            options={'verbose_name': '售货明细表', 'verbose_name_plural': '售货明细表'},
        ),
        migrations.AlterModelOptions(
            name='sales',
            options={'ordering': ['order_no'], 'verbose_name': '销售信息表', 'verbose_name_plural': '销售信息表'},
        ),
        migrations.AlterField(
            model_name='employee',
            name='sex',
            field=models.CharField(choices=[('F', '女'), ('M', '男')], max_length=1, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_id',
            field=models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='产品编号'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='order_no',
            field=models.ForeignKey(on_delete=True, to='salesapp.Sales', verbose_name='订单编号'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='prod_id',
            field=models.OneToOneField(max_length=5, on_delete=True, primary_key=True, serialize=False, to='salesapp.Product', verbose_name='产品名称'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='customer_id',
            field=models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='salesapp.Customer', verbose_name='客户号'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='sale_id',
            field=models.ForeignKey(max_length=5, on_delete=django.db.models.deletion.CASCADE, to='salesapp.Employee', verbose_name='员工编号'),
        ),
    ]
